
package br.com.fiap.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EndpointFinanceiroService", targetNamespace = "http://endpoint.fiap.com.br/", wsdlLocation = "http://54.191.197.37:8080/FinanceiroWS/EndpointFinanceiro?wsdl")
public class EndpointFinanceiroService
    extends Service
{

    private final static URL ENDPOINTFINANCEIROSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENDPOINTFINANCEIROSERVICE_EXCEPTION;
    private final static QName ENDPOINTFINANCEIROSERVICE_QNAME = new QName("http://endpoint.fiap.com.br/", "EndpointFinanceiroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://54.191.197.37:8080/FinanceiroWS/EndpointFinanceiro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENDPOINTFINANCEIROSERVICE_WSDL_LOCATION = url;
        ENDPOINTFINANCEIROSERVICE_EXCEPTION = e;
    }

    public EndpointFinanceiroService() {
        super(__getWsdlLocation(), ENDPOINTFINANCEIROSERVICE_QNAME);
    }

    public EndpointFinanceiroService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENDPOINTFINANCEIROSERVICE_QNAME, features);
    }

    public EndpointFinanceiroService(URL wsdlLocation) {
        super(wsdlLocation, ENDPOINTFINANCEIROSERVICE_QNAME);
    }

    public EndpointFinanceiroService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENDPOINTFINANCEIROSERVICE_QNAME, features);
    }

    public EndpointFinanceiroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EndpointFinanceiroService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EndpointFinanceiro
     */
    @WebEndpoint(name = "EndpointFinanceiroPort")
    public EndpointFinanceiro getEndpointFinanceiroPort() {
        return super.getPort(new QName("http://endpoint.fiap.com.br/", "EndpointFinanceiroPort"), EndpointFinanceiro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EndpointFinanceiro
     */
    @WebEndpoint(name = "EndpointFinanceiroPort")
    public EndpointFinanceiro getEndpointFinanceiroPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.fiap.com.br/", "EndpointFinanceiroPort"), EndpointFinanceiro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENDPOINTFINANCEIROSERVICE_EXCEPTION!= null) {
            throw ENDPOINTFINANCEIROSERVICE_EXCEPTION;
        }
        return ENDPOINTFINANCEIROSERVICE_WSDL_LOCATION;
    }

}
